apiVersion: v1
kind: Service
metadata:
  name: {{ include "goviolin-chart.fullname" . }}
  labels:
    {{- include "goviolin-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # 8080
      protocol: TCP
      name: http # 8080
      {{- if .Values.service.external }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "goviolin-chart.selectorLabels" . | nindent 4 }}
