apiVersion: v1
kind: Service
metadata:
  name: goviolin-service
spec:
  type: LoadBalancer
  selector:
    app: goviolin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007

